### ISSUE TITLE
Bug in the HUD

### ISSUE THREAD

**Issue by rezadarooei** [npruehs/ue4-rts#100]
Hi I found a bug in the HUD  when it is on the multiplayer mode it crashes. I've attached Log 
[RTS.log](https://github.com/npruehs/ue4-rts/files/2826944/RTS.log).

**Comment by npruehs** [comment]
Hey @rezadarooei!

Thanks for bringing this up. The crash is due to missing UPROPERTY macros for some UObject properties in ARTSPlayerController. The IsValid checks in the HUD class don't work as expected if these properties are not properly tagged as UPROPERTYs. More specifically, ARTSPlayerController::HoveredActor and ARTSPlayerController::SelectedActors need to be UPROPERTYs to prevent the crash you mentioned. As this is already fixed in the [release branch](https://github.com/npruehs/ue4-rts/tree/release/1.0), I'm not going to push the same fix to develop. I have attached a fixed version of 
[RTSPlayerController.zip](https://github.com/npruehs/ue4-rts/files/2829896/RTSPlayerController.zip) for convenience. Replace the file in ue4-rts\Source\RTS\Plugins\RTSPlugin\Source\RTSPlugin\Classes and you should be fine.
