### ISSUE TITLE
Can I set enemy units controlled by pc?

### ISSUE THREAD

**Issue by bbt636** [npruehs/ue4-rts#101]
Hello,
I love what you are doing and was trying to use it for some projects, i am not a programmer, i am a 3d designer but i like to use blueprints to make some functions, i wanted to know if it was possible to have a group of enemy units controlled by a pc that belong to a same team, not as another player but as neutral units that can attack the player

**Comment by bbt636** [comment]
Hello, 
I love what you are doing and was trying to use for some projects, i am not a programmer, i am a 3d designer but i like to use blueprints to make some functions, i wanted to know if it was possible to have a group of enemy units controlled by a pc that belong to a same team, not as another player but as  neutral units that can attack the player

**Comment by npruehs** [comment]
Hey @bbt636 ! We have that in our current game - a lot, actually. Our approach was to indeed have an RTSPlayerAIController that owns these units, the "neutral" player in our case. Depending on your game, you might even need two of them: For instance, WarCraft III has two dedicated players called "Neutral" and "Neutral Hostile".

**Comment by bbt636** [comment]
Let me see if i get it correctly, i have to make another player controller to neutral team and assign the units to it? Thanks

**Comment by bbt636** [comment]
Could you please explain it in more detail? i am not very good at programming as i said before, my deepest apologies for disturbing you.

**Comment by JaredP94** [comment]
Hi @npruehs,

Just to follow up on this thread, should we be creating the blackboard and behaviour tree for the AI used by the PlayerAIController? 

I don't see any kind of AI that relates to that control mechanism otherwise?

Thanks!

**Comment by npruehs** [comment]
@bbt636 Sorry for the late reply - somehow I didn't receive an e-mail, probably because your answers came so quickly after mine. Yes, exactly, in the current setup, you should be able to open SKM-DarkSpace as an example and take a closer look at everything.

Here, there are two player starts, BP_RTSPlayerStart with team index 0 and BP_RTSPlayerStart2 with team index 1. The blueprint Gameplay/BP_RTSGameMode does the rest of the setup: It has Num Teams set to 2, and Player AI Controller Class set to BP_RTSPlayerAIController. So if you're starting a game (e.g. by entering PIE), Unreal will assign the first player start to you. The game mode will parse any parameters, one of which is NumAIPlayers. Right now, this is hard to test in PIE, but you _could_ create another map which passes this parameter when loading the actual match map.
If you want neutral units on top of that, e.g. units that attack all players, you could just increase Num Teams in the game mode and add another player start for the team.

@JaredP94 Yes, that's exactly how AI players are controlled right now. Unfortunately, the plugin doesn't feature any examples for that (yet), because I haven't had the time to merge everything back. Basically, a sequence of calling GetNextPawnToProduce, CanPayFor and StartProduction should be enough to get you started already (along with specifying a build order at your AI controller blueprint of course).

**Comment by JaredP94** [comment]
@npruehs Makes perfect sense, thanks for elaborating on this! :)

**Comment by npruehs** [comment]
I'm closing this now for tracking purposes. Feel free to re-open in case you've still got any questions!

**Comment by npruehs** [comment]
Just to follow up on this one: 

* It's now possible to specify the number of AI players at the game mode directly (without having to pass parameters when loading a map), enabling you to test it in PIE
* There's a default implementation for player AI that carries out its build order.

Both can be found working in the example project as well.
