### ISSUE TITLE
Question around current Order System and Ability Order System

### ISSUE THREAD

**Issue by Zimbo1786** [npruehs/ue4-rts#146]
Hi @npruehs,

I was looking at the ability system (with the order system) you shared from the GDC presentation and was also looking at the order system for the RTS plugin. Looking at the earlier releases, you had a similar code layout in the plugin but looking at the latest release it has changed quite a bit. 

I was just wondering around the reasoning? Is it to make the order system more generalised and allow custom orders? Is it because you have seen an opportunity to optimise? 

Thanks for taking the time to read through this - just want to expand on my learning. Have learnt a lot from your coding as I have been tweaking and trying to integrate the two.

**Comment by npruehs** [comment]
Hey @Zimbo1786,

yes, I've learned quite a bit myself making the plugin (and creating A Year Of Rain with it). Somehow, I felt the urge to apply all my learnings, and some of them were quite fundamental, as you've noticed:

- renaming the plugin to match other Unreal Engine plugin names
- using subfolders by feature
- merging back features, bugfixes and performance optimizations from A Year Of Rain
- splitting up utility libraries for better includes
- using gameplay tags for more flexibility now and in the future

I found that it's hard to apply all this without fundamentally changing the plugin in some ways, and here's the result :)

**Comment by Zimbo1786** [comment]
Thanks @npruehs for the explanation and that we could benefit from your learnings. Much appreciated!

**Comment by Zimbo1786** [comment]
Hi @npruehs,

I was also looking through and noticed that through the abilities system, the orders (attack, move etc.) had their own behaviour tree as opposed to this plugin that has just one behaviour tree. I was wondering if there was any particular reason - is the plugin's single behaviour tree a placeholder or an optimisation compared to the abilities system or does the abilities system individual behaviour trees offer more flexibility?

**Comment by npruehs** [comment]
Strange. I could swear I had answered this one already.

Yes, in fact, the abilities system individual behaviour trees offer more flexibility. More specifically, they allow you to add additional orders to the game, which could be basically anything (for A Year Of Rain, we had "Pick Up Item", for instance).

**Comment by Zimbo1786** [comment]
Hi @npruehs,

Thanks for the reply - yes you have. Apologies - it may have been how I phrased the original question which was more geared to the overall order/ability system as opposed to the individual behaviour trees. Thanks for the response though.

**Comment by coolyoshi** [comment]
@npruehs 
Thanks to your help I was able to solve my issue where spamming move order would cause unit to stutter by avoiding restarting the behavior tree if calling the same order repeatedly.  But I'm still noticing some stutter when switching between different behavior trees (e.g. switching from move order to attack order). I'm guessing this stutter is also caused by starting up behavior trees. Do you know how I might be able to avoid starting behavior trees when switching trees or if there might be some other solution?

**Comment by npruehs** [comment]
None that I'm aware of :/ But feel free to share any insights you're able to gain! :)

**Comment by coolyoshi** [comment]
I see thanks! Sure if I can find out anything i'll post it here

**Comment by coolyoshi** [comment]
Hmm turns out for my case the stuttering was caused by the AI calling "Finish Execute" between separate move tasks. This answer kind of explains it a bit more: https://answers.unrealengine.com/questions/557677/ai-character-stopspauses-after-move-to-node.html.

Not sure if this is the best solution but I fixed my stuttering by replacing the AI Move To node with a custom move task. Inside the task I call the "AI MoveTo" node except only call Finish Execute on the success callback. Then I made sure each order that uses the new move to task restarts the behavior tree

Update: nvm this makes it so you can't abort move orders properly
Update2: workaround for above issue is to call AI Controller "Stop Movement" whenever character needs to stop (e.g. for hold position order or on death)

**Comment by npruehs** [comment]
Interesting.

Make sure you handle failed MoveTo properly (e.g. no path found). Once, we had an issue where units had infinite range when you ordered them to attack a target that was unreachable (e.g. on the other side of a cliff). Our "move into range" node failed, but that wasn't handled properly and the unit happily attacked the target anyway :)

**Comment by coolyoshi** [comment]
Wow that's a crazy bug lol. Anyways good point, I'll have to add in some handling for when it actually fails
