### ISSUE TITLE
Camera Movement

### ISSUE THREAD

**Issue by ImperatorJuri** [npruehs/ue4-rts#201]
Moin,

leider kann ich die im Bild dargestellten drei Aktionen nicht finden, wo kann man diese denn eintragen?

Im Falle von Inputs in Project Settings muss man Up/Down Left/Right trennen nehme ich an.

![image](https://user-images.githubusercontent.com/115213142/194744921-78911ecc-bad9-49c9-9b92-fdb53fd5acfa.png)
_________

Hey,

sadly I can't find the three camera movement commands, can anyone tell me pls where I can define them?

In case of Projectsettings Input I assume the Up/Down and Left/Right commands need to be seperated.

![image](https://user-images.githubusercontent.com/115213142/194744921-78911ecc-bad9-49c9-9b92-fdb53fd5acfa.png)

**Comment by npruehs** [comment]
Hey @ImperatorJuri !
You're correct, these are referring to Project Settings > Input.
There's no way to "find" them, you'll have to define them there yourself, by just specifying these exact names.
Because you need to define _axes_ (as opposed to _actions_), you'll need to bind both Left/Right to the same axis.
