### ISSUE TITLE
Vision volume causing massive frame drops. Deleting it and pressing play crashes the engine.

### ISSUE THREAD

**Issue by Tdead1** [npruehs/ue4-rts#75]
Leaving the vision volume in the base sample level causes frame times to shoot up to ~40ms. The way around it is to change the size per tile variable to higher (64 gives ~60fps) but that messes up the vision volume. 

Removing it from the level crashes the engine. We are using version 4.19.2 of Unreal. Might have to do with the upgrade?

**Comment by npruehs** [comment]
Hey @Tdead1 ,

I can observe the same on my side, using Unreal 4.18.3. From the top of my head, I know that we've done some performance optimization on that in our current title, but that was after 1000s of actors to the level. I can't remember anything else specific that we've done here, but it's been quite a while.

I need to dig deeper and profile into what exactly is causing the issue here.

Sorry I don't have better news right now for you.

**Comment by npruehs** [comment]
There you go. Just pull from develop again.

You'll need to set the FogOfWarMaterial of your RTSMinimapWidget to M_RTSFogOfWarMinimap, and you should be fine now.

**Comment by Tdead1** [comment]
Ah, great, I'll ask my team to try it now. Thanks a bunch!

**Comment by Tdead1** [comment]
Just want to confirm that it works now. Thanks again!

**Comment by npruehs** [comment]
Thanks for the feedback! :)
